#define NUM_CARDS_IN_DECK 52

#define ACE_SYMBOL 'A'
#define TEN_SYMBOL 'T'
#define JACK_SYMBOL 'J'
#define QUEEN_SYMBOL 'Q'
#define KING_SYMBOL 'K'

#define HEART_SYMBOL "\u2665"
#define DIAMOND_SYMBOL "\u25C6"
#define CLUB_SYMBOL "\u2663"
#define SPADE_SYMBOL "\u2660"

#define TRUE 1
#define FALSE 0

#define TEST_HANDS 9
#define TEST_CARDS 5

enum handRanks { HIGH_CARD, ONE_PAIR, TWO_PAIR, TRIPLET, STRAIGHT, FLUSH, FULL_HOUSE, FOUR_OF_A_KIND, STRAIGHT_FLUSH };
